name: wikinet
channels:
  - plotly
  - conda-forge
dependencies:
  - python=3.7
  - cmake
  - jupyter
  - numpy
  - scipy
  - pandas>1.0.0
  - matplotlib
  - networkx
  - gensim
  - python-Levenshtein
  - pygraphviz
  - cython
  - sphinx # documentation
  - jupyter_contrib_nbextensions
  - nbconvert=5.6.1 # https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1529#issuecomment-695057809
  - ipywidgets # interactivity
  - plotly
  - plotly-orca # saving plotly
  - psutil # saving plotly
  - leidenalg
  - python-igraph
  - dill
  - pip
  - pip:
    - bctpy>=0.5.2
    - mwparserfromhell
    - sklearn
    - dionysus<=2.0.7 # not sure why this is failing the conda install
    - cpnet==0.0.6 # >0.0.6 has no source
    - powerlaw
    - cufflinks
    - rpy2
    - build
    - twine
    - sphinx-rtd-theme
