name: wikinet
channels:
  - plotly
  - conda-forge
dependencies:
  - python=3.7
  - jupyter
  - numpy
  - scipy
  - pandas>1.0.0
  - matplotlib
  - networkx
  - gensim
  - pygraphviz
  - mpmath # for powerlaw
  - cython
  - sphinx # documentation
  - jupyter_contrib_nbextensions
  - nbconvert=5.6.1 # https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1529#issuecomment-695057809
  - ipywidgets # interactivity
  - plotly
  - plotly-orca # saving plotly
  - psutil # saving plotly
  - leidenalg
  - python-igraph
  - pip
  - pip:
    - bctpy>=0.5.2
    - mwparserfromhell
    - sklearn
    - dionysus
    - pybind11
    - cpnet
    - powerlaw
    - sphinx_rtd_theme
    - cufflinks
    - dill
    - rpy2
    - build
    - twine
