name: wikinet-rtd
channels:
  - conda-forge
dependencies:
  - python=3.7
  - cmake
  - boost-cpp
  - numpy
  - scipy
  - pandas>1.0.0
  - networkx
  - gensim
  - python-levenshtein
  - pip
  - pip:
    - bctpy>=0.5.2
    - mwparserfromhell
    - sklearn
    - dionysus
    - cpnet<=0.0.6
